pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    demo:
                        items: {  }
                        medias: {  }
                        name: demo
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1688730299
                        creationDate: 1688730299
                        preserveAnimation: false
