doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: tomek, password: Master12, dbname: pimtest, mapping_types: { enum: string, bit: boolean }, server_version: 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1 } } }
