<?php

namespace ContainerExGpjeR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4KCCa9IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4KCCa9I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4KCCa9I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exportService' => ['services', 'Pimcore\\Bundle\\DataHubBundle\\Service\\ExportService', 'getExportServiceService', true],
        ], [
            'exportService' => 'Pimcore\\Bundle\\DataHubBundle\\Service\\ExportService',
        ]);
    }
}
