<?php

namespace ContainerExGpjeR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\DataHubBundle\Service\ImportService' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataHubBundle\Service\ImportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/Service/ImportService.php';

        $a = ($container->services['Pimcore\\Extension\\Bundle\\PimcoreBundleManager'] ?? self::getPimcoreBundleManagerService($container));

        if (isset($container->services['Pimcore\\Bundle\\DataHubBundle\\Service\\ImportService'])) {
            return $container->services['Pimcore\\Bundle\\DataHubBundle\\Service\\ImportService'];
        }

        return $container->services['Pimcore\\Bundle\\DataHubBundle\\Service\\ImportService'] = new \Pimcore\Bundle\DataHubBundle\Service\ImportService($a, ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
