<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B3wKka1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B3wKka1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B3wKka1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'messenger.transport.pimcore_asset_update' => ['privates', 'messenger.transport.pimcore_asset_update', 'getMessenger_Transport_PimcoreAssetUpdateService', true],
            'messenger.transport.pimcore_core' => ['privates', 'messenger.transport.pimcore_core', 'getMessenger_Transport_PimcoreCoreService', true],
            'messenger.transport.pimcore_failed_jobs' => ['privates', 'messenger.transport.pimcore_failed_jobs', 'getMessenger_Transport_PimcoreFailedJobsService', true],
            'messenger.transport.pimcore_image_optimize' => ['privates', 'messenger.transport.pimcore_image_optimize', 'getMessenger_Transport_PimcoreImageOptimizeService', true],
            'messenger.transport.pimcore_maintenance' => ['privates', 'messenger.transport.pimcore_maintenance', 'getMessenger_Transport_PimcoreMaintenanceService', true],
            'messenger.transport.pimcore_scheduled_tasks' => ['privates', 'messenger.transport.pimcore_scheduled_tasks', 'getMessenger_Transport_PimcoreScheduledTasksService', true],
            'pimcore_asset_update' => ['privates', 'messenger.transport.pimcore_asset_update', 'getMessenger_Transport_PimcoreAssetUpdateService', true],
            'pimcore_core' => ['privates', 'messenger.transport.pimcore_core', 'getMessenger_Transport_PimcoreCoreService', true],
            'pimcore_failed_jobs' => ['privates', 'messenger.transport.pimcore_failed_jobs', 'getMessenger_Transport_PimcoreFailedJobsService', true],
            'pimcore_image_optimize' => ['privates', 'messenger.transport.pimcore_image_optimize', 'getMessenger_Transport_PimcoreImageOptimizeService', true],
            'pimcore_maintenance' => ['privates', 'messenger.transport.pimcore_maintenance', 'getMessenger_Transport_PimcoreMaintenanceService', true],
            'pimcore_scheduled_tasks' => ['privates', 'messenger.transport.pimcore_scheduled_tasks', 'getMessenger_Transport_PimcoreScheduledTasksService', true],
        ], [
            'messenger.transport.pimcore_asset_update' => '?',
            'messenger.transport.pimcore_core' => '?',
            'messenger.transport.pimcore_failed_jobs' => '?',
            'messenger.transport.pimcore_image_optimize' => '?',
            'messenger.transport.pimcore_maintenance' => '?',
            'messenger.transport.pimcore_scheduled_tasks' => '?',
            'pimcore_asset_update' => '?',
            'pimcore_core' => '?',
            'pimcore_failed_jobs' => '?',
            'pimcore_image_optimize' => '?',
            'pimcore_maintenance' => '?',
            'pimcore_scheduled_tasks' => '?',
        ]);
    }
}
