<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D_JGTzXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d.jGTzX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d.jGTzX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bundleManager' => ['services', 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager', 'getPimcoreBundleManagerService', false],
            'config' => ['services', 'Pimcore\\Config', 'getConfigService', false],
            'csrfProtection' => ['services', 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler', 'getCsrfProtectionHandlerService', false],
            'kernel' => ['services', 'kernel', 'getKernelService', false],
            'maintenanceExecutor' => ['privates', 'Pimcore\\Maintenance\\Executor', 'getExecutorService', true],
        ], [
            'bundleManager' => 'Pimcore\\Extension\\Bundle\\PimcoreBundleManager',
            'config' => 'Pimcore\\Config',
            'csrfProtection' => 'Pimcore\\Bundle\\AdminBundle\\Security\\CsrfProtectionHandler',
            'kernel' => '?',
            'maintenanceExecutor' => 'Pimcore\\Maintenance\\Executor',
        ]);
    }
}
