<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PsUk7naService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.psUk7na' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.psUk7na'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'importService' => ['services', 'Pimcore\\Bundle\\DataHubBundle\\Service\\ImportService', 'getImportServiceService', true],
        ], [
            'importService' => 'Pimcore\\Bundle\\DataHubBundle\\Service\\ImportService',
        ]);
    }
}
