<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WtdQQQjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WtdQQQj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WtdQQQj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pimcore_failed_jobs' => ['privates', 'messenger.transport.pimcore_failed_jobs', 'getMessenger_Transport_PimcoreFailedJobsService', true],
        ], [
            'pimcore_failed_jobs' => '?',
        ]);
    }
}
