<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\DataHubBundle\Service\ExportService' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataHubBundle\Service\ExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/Service/ExportService.php';

        return $container->services['Pimcore\\Bundle\\DataHubBundle\\Service\\ExportService'] = new \Pimcore\Bundle\DataHubBundle\Service\ExportService();
    }
}
