<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Main\MainController' shared autowired service.
     *
     * @return \App\Controller\Main\MainController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/Controller.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/FrontendController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Main/MainController.php';

        $container->services['App\\Controller\\Main\\MainController'] = $instance = new \App\Controller\Main\MainController();

        $instance->setContainer(($container->privates['.service_locator.jIByowl'] ?? $container->load('get_ServiceLocator_JIByowlService'))->withContext('App\\Controller\\Main\\MainController', $container));

        return $instance;
    }
}
