<?php

namespace Container9dkAIKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemSettingsConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\SystemSettingsConfig' shared autowired service.
     *
     * @return \Pimcore\SystemSettingsConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/SystemSettingsConfig.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Pimcore\\SystemSettingsConfig'])) {
            return $container->services['Pimcore\\SystemSettingsConfig'];
        }

        return $container->services['Pimcore\\SystemSettingsConfig'] = new \Pimcore\SystemSettingsConfig($a, ($container->services['Pimcore\\Localization\\LocaleServiceInterface'] ?? self::getLocaleServiceInterfaceService($container)));
    }
}
