<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9dkAIKW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9dkAIKW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9dkAIKW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9dkAIKW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9dkAIKW\App_KernelDevDebugContainer([
    'container.build_hash' => '9dkAIKW',
    'container.build_id' => '28b4178d',
    'container.build_time' => 1690536181,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9dkAIKW');
