<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB254nMU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB254nMU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB254nMU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB254nMU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB254nMU\App_KernelDevDebugContainer([
    'container.build_hash' => 'B254nMU',
    'container.build_id' => '24f3a757',
    'container.build_time' => 1690551313,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB254nMU');
